-- Seed cars id 12 to 100 (ids 1-11 already inserted)
-- The `id` column is omitted so the serial primary key is assigned automatically.

INSERT INTO "cars" ("make", "model", "year", "color", "number_of_doors", "price_per_day", "available", "description") VALUES
  ('Chevrolet',     'Malibu',              2021, 'Navy',   4, 47,  FALSE, 'Mid-size sedan offering a smooth ride, roomy cabin, and practical features for family travel.'),
  ('Mazda',         'CX-5',                2023, 'Red',    4, 68,  TRUE,  'Stylish crossover SUV with sporty handling, premium interior feel, and excellent safety features.'),
  ('Subaru',        'Outback',             2022, 'Brown',  4, 71,  TRUE,  'Adventure-ready wagon with all-wheel drive, generous cargo space, and dependable year-round capability.'),
  ('Tesla',         'Model 3',             2024, 'White',  4, 110, FALSE, 'All-electric sedan delivering quick acceleration, advanced driver assistance, and minimalist design.'),
  ('Lexus',         'RX 350',              2023, 'Silver', 4, 102, TRUE,  'Premium SUV known for quiet comfort, refined ride quality, and a spacious upscale interior.'),
  ('Volvo',         'XC60',                2022, 'Blue',   4, 98,  TRUE,  'Safety-focused luxury SUV with elegant Scandinavian design and confident all-around performance.'),
  ('Porsche',       'Macan',               2021, 'Black',  4, 130, FALSE, 'Performance-oriented compact luxury SUV combining athletic driving dynamics with everyday practicality.'),
  ('Renault',       'Megane',              2020, 'Gray',   4, 44,  TRUE,  'Comfortable hatchback with efficient fuel usage, practical layout, and easy urban maneuverability.'),
  ('Peugeot',       '3008',                2023, 'Green',  4, 66,  TRUE,  'Modern crossover featuring distinctive styling, flexible cabin space, and smooth long-distance comfort.'),
  ('Toyota',        'RAV4',                2023, 'Silver', 4, 72,  TRUE,  'Best-selling compact SUV with all-wheel drive, generous cargo space, and outstanding reliability.'),
  ('Honda',         'CR-V',                2022, 'White',  4, 68,  TRUE,  'Family-friendly crossover with a refined cabin, excellent fuel economy, and advanced safety suite.'),
  ('Ford',          'Explorer',            2021, 'Black',  4, 88,  FALSE, 'Three-row SUV offering ample seating, strong towing capability, and rugged trail-ready performance.'),
  ('Chevrolet',     'Equinox',             2022, 'Blue',   4, 58,  TRUE,  'Value-focused compact SUV with comfortable seating, solid safety scores, and easy tech features.'),
  ('Nissan',        'Rogue',               2023, 'Red',    4, 63,  TRUE,  'Versatile family SUV with ProPilot driver assist, spacious cabin, and smooth highway ride.'),
  ('BMW',           '3 Series',            2022, 'Gray',   4, 95,  TRUE,  'Sport-tuned executive sedan combining precise handling with upscale interior craftsmanship.'),
  ('Mercedes-Benz', 'E-Class',             2023, 'Silver', 4, 115, FALSE, 'Flagship luxury saloon with a pillow-soft ride, opulent cabin, and comprehensive driver aids.'),
  ('Audi',          'Q5',                  2022, 'White',  4, 105, TRUE,  'Polished all-road SUV with quattro traction, virtual cockpit dashboard, and premium build quality.'),
  ('Volkswagen',    'Tiguan',              2021, 'Orange', 4, 64,  TRUE,  'Practical family SUV with an intuitive infotainment system and comfortable long-distance capability.'),
  ('Hyundai',       'Tucson',              2023, 'Black',  4, 61,  TRUE,  'Attractively styled compact SUV with a feature-packed cabin and a generous standard warranty.'),
  ('Kia',           'Sorento',             2022, 'Brown',  4, 74,  FALSE, 'Three-row family SUV balancing smart cargo flexibility with a refined and quiet interior.'),
  ('Mazda',         '3',                   2023, 'Red',    4, 55,  TRUE,  'Premium compact hatchback with driver-focused cabin, upscale materials, and agile handling.'),
  ('Subaru',        'Forester',            2022, 'Green',  4, 67,  TRUE,  'Outdoor-ready SUV with symmetrical AWD, expansive visibility, and rugged weekend versatility.'),
  ('Toyota',        'Camry',               2024, 'Blue',   4, 60,  TRUE,  'Mid-size sedan renowned for decades of reliability, spacious interior, and efficient hybrid option.'),
  ('Honda',         'Accord',              2023, 'Gray',   4, 58,  FALSE, 'Refined family sedan with turbocharged performance, expansive rear legroom, and intuitive technology.'),
  ('Ford',          'F-150',               2022, 'White',  4, 92,  TRUE,  'America''s best-selling pickup with tough towing ability, innovative bed features, and Pro Power Onboard.'),
  ('Ram',           '1500',                2023, 'Black',  4, 95,  TRUE,  'Award-winning half-ton truck offering a coil-spring rear suspension for best-in-class ride comfort.'),
  ('Chevrolet',     'Silverado 1500',      2021, 'Red',    4, 89,  TRUE,  'Capable full-size truck with a wide engine selection, Trailering app, and durable cargo management.'),
  ('Tesla',         'Model Y',             2024, 'Silver', 4, 120, FALSE, 'Electric crossover with 330-mile range, instant torque, and over-the-air software improvements.'),
  ('BMW',           'X3',                  2021, 'Blue',   4, 98,  TRUE,  'Compact luxury SUV balancing everyday practicality with the driving dynamics BMW is known for.'),
  ('Mercedes-Benz', 'GLC',                 2022, 'White',  4, 112, TRUE,  'Best-selling Mercedes SUV with a plush ride, elegantly trimmed interior, and advanced safety tech.'),
  ('Audi',          'A6',                  2022, 'Gray',   4, 118, FALSE, 'Executive sedan with mild-hybrid efficiency, quattro all-wheel drive, and a panoramic sunroof.'),
  ('Volvo',         'S90',                 2021, 'Navy',   4, 108, TRUE,  'Flagship Scandinavian luxury saloon with crystal-clear interior lighting, plug-in hybrid option.'),
  ('Lexus',         'ES 300h',             2023, 'Black',  4, 107, TRUE,  'Hybrid luxury sedan with whisper-quiet cabin, outstanding reliability, and serene ride quality.'),
  ('Porsche',       'Cayenne',             2023, 'Red',    4, 155, TRUE,  'Iconic performance SUV combining sports-car agility with genuine family-hauling practicality.'),
  ('Land Rover',    'Discovery',           2022, 'Green',  4, 138, FALSE, 'Seven-seat luxury SUV with outstanding off-road terrain response and a sumptuous interior.'),
  ('Jeep',          'Grand Cherokee',      2023, 'Silver', 4, 99,  TRUE,  'Refined American SUV with Quadra-Lift air suspension, Uconnect 5 display, and 4xe plug-in option.'),
  ('Hyundai',       'Santa Fe',            2022, 'White',  4, 77,  TRUE,  'Mid-size SUV with bold exterior design, spacious cabin materials, and standard safety features.'),
  ('Kia',           'Telluride',           2024, 'Brown',  4, 86,  TRUE,  'Highly rated three-row SUV with upscale finishes, generous standard features, and relaxed cruise ability.'),
  ('Mazda',         'CX-9',                2021, 'Blue',   4, 83,  FALSE, 'Three-row family crossover that delivers near-luxury refinement at a mainstream price point.'),
  ('Nissan',        'Pathfinder',          2022, 'Orange', 4, 80,  TRUE,  'Three-row SUV redesigned for 2022 with a nine-speed transmission and a more car-like driving feel.'),
  ('Toyota',        'Highlander',          2023, 'Gray',   4, 85,  TRUE,  'Popular three-row SUV with a hybrid powertrain option, ample safety tech, and premium interior.'),
  ('Ford',          'Edge',                2021, 'Black',  4, 70,  TRUE,  'Mid-size SUV with sporty ST trim option, panoramic rooftop, and available Ford Co-Pilot360.'),
  ('Honda',         'Pilot',               2023, 'Red',    4, 81,  FALSE, 'Spacious three-row family SUV with TrailSport off-road variant and redesigned interior for 2023.'),
  ('Volkswagen',    'Passat',              2020, 'Silver', 4, 52,  TRUE,  'Full-size sedan value champion with a roomy backseat, quiet ride, and solid reliability record.'),
  ('Skoda',         'Octavia',             2022, 'White',  4, 48,  TRUE,  'Practical European family car with estate and hatchback body styles and a class-leading boot space.'),
  ('Seat',          'Leon',                2021, 'Blue',   4, 43,  TRUE,  'Sporty compact hatchback with dynamic styling, powerful TSI engines, and responsive steering.'),
  ('Opel',          'Astra',               2023, 'Gray',   4, 46,  FALSE, 'Newly redesigned compact hatchback with plug-in hybrid option and IntelliLux pixel LED headlights.'),
  ('Citroen',       'C5 Aircross',         2022, 'Green',  4, 59,  TRUE,  'French crossover with Progressive Hydraulic Cushions suspension, modular rear seating, and sleek design.'),
  ('Toyota',        'Land Cruiser',        2024, 'Black',  4, 145, TRUE,  'Legendary off-road SUV with Multi-Terrain Select, KDSS suspension, and unmatched global durability.'),
  ('Mercedes-Benz', 'GLE',                 2023, 'White',  4, 135, TRUE,  'Flagship mid-size luxury SUV with AIRMATIC suspension, E-ACTIVE BODY CONTROL, and commanding presence.'),
  ('BMW',           '5 Series',            2022, 'Blue',   4, 122, FALSE, 'Upper executive sedan with a perfect balance of sport, comfort, and cutting-edge driver assistance.'),
  ('Audi',          'Q7',                  2021, 'Silver', 4, 130, TRUE,  'Large three-row luxury SUV with air suspension, MMI touchscreen, and quattro ultra AWD system.'),
  ('Lexus',         'NX 350',              2023, 'Red',    4, 96,  TRUE,  'Fully redesigned compact luxury SUV with a tazuna cockpit, large touchscreen, and quickened performance.'),
  ('Alfa Romeo',    'Giulia',              2022, 'Red',    4, 109, FALSE, 'Italian sport sedan with rear-wheel drive, Ferrari-derived engine option, and stunning coupe-like profile.'),
  ('Alfa Romeo',    'Stelvio',             2023, 'Gray',   4, 116, TRUE,  'Performance SUV with sharp steering, standard RWD, and interior style that rivals German competitors.'),
  ('Jaguar',        'F-Pace',              2021, 'Black',  4, 128, TRUE,  'Elegant British performance SUV with Pivi Pro infotainment, adaptive dynamics, and supercharged V8 option.'),
  ('Land Rover',    'Range Rover Sport',   2023, 'White',  4, 162, TRUE,  'High-performance Range Rover variant blending sports dynamics with all-terrain luxury SUV versatility.'),
  ('Genesis',       'GV80',                2022, 'Silver', 4, 121, FALSE, 'Korean luxury SUV making a bold statement with crest grille styling and aircraft-inspired interior.'),
  ('Genesis',       'G80',                 2023, 'Blue',   4, 117, TRUE,  'Sophisticated luxury sedan with electrified AWD option, ERGO MOTION seats, and 5-star safety ratings.'),
  ('Subaru',        'Crosstrek',           2022, 'Orange', 4, 54,  TRUE,  'Rugged compact crossover with elevated ground clearance, standard AWD, and e-BOXER hybrid option.'),
  ('Mitsubishi',    'Outlander',           2023, 'Black',  4, 63,  TRUE,  'Three-row SUV with plug-in hybrid powertrain, S-AWC all-wheel control, and spacious redesigned cabin.'),
  ('Fiat',          '500X',                2021, 'Yellow', 4, 49,  TRUE,  'Italian-flavoured compact crossover with retro-modern styling, agile city handling, and cheerful interior.'),
  ('Mini',          'Countryman',          2022, 'Green',  4, 75,  FALSE, 'The most practical Mini yet, with available ALL4 AWD, premium materials, and a sporty John Cooper Works variant.'),
  ('Toyota',        'Prius',               2024, 'Silver', 4, 57,  TRUE,  'Revamped hybrid icon with bold new styling, improved performance, and class-leading fuel economy.'),
  ('Hyundai',       'IONIQ 6',             2023, 'White',  4, 95,  TRUE,  'Streamlined electric sedan with 361-mile range, fast 800V charging architecture, and minimalist design.'),
  ('Kia',           'EV6',                 2024, 'Red',    4, 100, FALSE, 'Award-winning electric crossover with dual-motor AWD, ultra-fast 350kW charging, and spacious frunk.'),
  ('Volkswagen',    'ID.4',                2023, 'Blue',   4, 88,  TRUE,  'All-electric family SUV with a flat floor, 275-mile range, and over-the-air update capability.'),
  ('BMW',           'iX3',                 2022, 'Gray',   4, 114, TRUE,  'Pure electric compact SUV offering 285-mile range, fifth-generation eDrive system, and refined interior.'),
  ('Mercedes-Benz', 'EQB',                 2023, 'Black',  4, 118, TRUE,  'Electric seven-seat SUV with modular EQ platform, MBUX smart assistant, and up to 260-mile range.'),
  ('Renault',       'Kadjar',              2020, 'Orange', 4, 51,  TRUE,  'Practical French compact SUV with commanding driving position, decent boot space, and smooth ride.'),
  ('Peugeot',       '508',                 2022, 'Gray',   4, 72,  FALSE, 'Bold fastback sedan with lion''s claw LED daytime running lights and an i-Cockpit digital interior.'),
  ('Seat',          'Ateca',               2021, 'White',  4, 58,  TRUE,  'Spanish compact SUV sharing mechanicals with Golf, offering a dynamic drive and practical cabin.'),
  ('Skoda',         'Karoq',               2022, 'Brown',  4, 56,  TRUE,  'Sensible all-rounder SUV with VarioFlex rear seats, large boot, and Simply Clever storage solutions.'),
  ('Opel',          'Grandland',           2023, 'Blue',   4, 60,  TRUE,  'Euro compact SUV with plug-in hybrid powertrain, Pixel LED matrix headlights, and panoramic roof.'),
  ('Ford',          'Kuga',                2022, 'Silver', 4, 65,  FALSE, 'Efficient PHEV family SUV with 35-mile electric-only range and an intuitive SYNC 4 infotainment system.'),
  ('Toyota',        'C-HR',                2023, 'Red',    4, 61,  TRUE,  'Sharp-edged hybrid crossover with dynamic styling, agile handling, and low fuel consumption in town.'),
  ('Honda',         'HR-V',                2022, 'Green',  4, 57,  TRUE,  'Efficient e:HEV subcompact SUV with clever Magic Seat, ultra-low NVH levels, and smooth ride quality.'),
  ('Nissan',        'Qashqai',             2023, 'Yellow', 4, 59,  TRUE,  'Original crossover pioneer now with e-POWER series-hybrid drivetrain and ProPILOT highway assist.'),
  ('Dacia',         'Duster',              2022, 'Orange', 4, 36,  TRUE,  'Budget-friendly off-road capable SUV offering impressive value, 4WD option, and rugged reliability.'),
  ('Suzuki',        'Vitara',              2021, 'Blue',   4, 46,  FALSE, 'Compact SUV known for its ALLGRIP four-wheel drive system and nimble citified handling.'),
  ('Mitsubishi',    'Eclipse Cross',       2022, 'White',  4, 54,  TRUE,  'Coupe-inspired SUV with twin-scroll turbocharged engine, split-screen rear window, and S-AWC system.'),
  ('Mazda',         'CX-30',               2023, 'Red',    4, 60,  TRUE,  'Sleek subcompact SUV with SKYACTIV-X engine, elevated driving position, and near-premium cabin.'),
  ('Volvo',         'XC40',                2022, 'Gray',   4, 86,  TRUE,  'Safety-first subcompact luxury SUV with clever storage, Google built-in infotainment, and Recharge EV twin.'),
  ('Audi',          'Q3',                  2021, 'Navy',   4, 82,  FALSE, 'Entry luxury SUV with MIB 3 infotainment, virtual cockpit, and quattro all-wheel drive on higher trims.'),
  ('BMW',           'X1',                  2023, 'Black',  4, 84,  TRUE,  'New-generation compact luxury SUV with a curved iDrive display, plug-in hybrid, and xDrive AWD.'),
  ('Ford',          'Puma',                2022, 'Yellow', 4, 50,  TRUE,  'Sporty urban crossover with a 155-litre MegaBox storage under the boot floor and mild-hybrid engine.'),
  ('Hyundai',       'Kona Electric',       2024, 'Orange', 4, 79,  TRUE,  'Fully electric subcompact SUV redesigned for 2024 with 300-mile range and a bold new exterior look.'),
  ('Chevrolet',     'Blazer EV',           2024, 'Red',    4, 93,  FALSE, 'All-electric Blazer with SS performance trim delivering 557 hp, Super Cruise, and 320-mile range.'),
  ('Toyota',        'bZ4X',                2023, 'White',  4, 82,  TRUE,  'Toyota''s first dedicated BEV with a yoke steering wheel concept, solar roof option, and 250-mile range.');
